import Video from './Video.js'

/**
 * ? Stefan AI Video Script Interface
 * @interface StefanAIVideoScript
 * * Represents a video script object, which is generated by Stefan AI.
 * * Contains multiple videos.
 */
export default interface StefanAIVideoScript {
    error?: string
    [key: string]: Video | string | undefined
}