/**
 * ? Timing Interface
 * @interface Timing
 * * Represents a timing object, with values for MFA data.
 * * Data represents the start and end time of a word, and the word itself.
 * * Used in this specific case, to parse the TextGrid file generated by MFA, word by work
 */
export default interface Timing {
    xmin: number
    xmax: number
    text: string
}