/**
 * ? Video Interface
 * @interface Video
 * * Represents a video object, which is apart of the @interface StefanAIVideoScript Interface.
 * * Used in this specific case, to parse the JSON file individiual data generated by Stefan AI.
 * * Data represents the message, and whether or not the video is used, and whether or not the video extends, to another
 * * To extend means that a video transitions quicker to the other one. 
 */
export default interface Video {
    isUsed?: boolean
    extends?: boolean
    message?: string
}
